### ISSUE TITLE
2nd browser language is ignored

### ISSUE THREAD

**Issue by flossels** [Leuchtfeuer/locate#13]
If my browser supports multiple languages (eg FR-DE-EN) and there is no dedicated condition for FR (but one for DE and the default one for EN), the default condition will be applied.

**Comment by urbantrout** [comment]
Thanks for this plugin! Unfortunately this bug makes it unusable… Are there any plans on fixing this issue?

**Comment by FlorianWessels** [comment]
Hi urbantrout,

thanks for your interest in our extension (and pushing this).
Yes, we are working on that, but we still have some logical problems there (ordering of TypoScript settings)... nevertheless, this has to be fixed with the next release.

**Comment by FlorianWessels** [comment]
HI @urbantrout,

this problem should be solved in current master. Feel free to test this "feature".

Thanks,
Florian
