### ISSUE TITLE
static_countries table is not up to date

### ISSUE THREAD

**Issue by majernik** [Leuchtfeuer/locate#20]
**Describe the bug**
The table static_countries is not up to date and needs to be updated.

**To Reproduce**
1. Set manually IP-Address to 217.91.35.16
2. When process function of IP2Country is called, no result is found

**Expected behavior**
Germany is found

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by flossels** [comment]
This issue is invalid as the query `select * from static_ip2country_v4 where ip_from <= 3646628624 AND ip_to >= 3646628624;` returns the country code `DE` which is the expected behaviour. Maybe you forget to run the database update script in the extension manager?
