### ISSUE TITLE
Countrycode cannot be resolved to IPv6

### ISSUE THREAD

**Issue by derBoogie** [Leuchtfeuer/locate#23]
Hi,
I need the resolution of the client IP to the country for my extension.
So I installed locate and used the function LocateUtility::getCountryIso2FromIP.
Unfortunately, this does not return a country code for the client PI v6 (v4 works).
So I debugged and found that the typecast to integer in function getNumericIp line 49
```return (int)base_convert(ltrim($binNum, '0'), 2, 10);```
changes the decimal value so that it cannot be resolved in the database.
If you omit the typecast, then it works.

TYPO3: v10.4.17
locate: v10.0.2

**Comment by elbebass** [comment]
This is already [fixed](https://github.com/Leuchtfeuer/locate/commit/3425684aa7f602ec7ae551fa0432fff29fd26d5a) in the current beta. I will take this into discussion, hope until then this will work out for you

**Comment by elbebass** [comment]
At the moment we do not have plans to release a version before moving the beta to a stable version. Sorry.

**Comment by flossels** [comment]
Hi,

IPv6 detection is already improved in the master of v10 (see: https://github.com/Leuchtfeuer/locate/commit/355b48c78f900b1c938997ede7c3c521c67ae29d). You can simply use this version or even better: A version 10.0.3 should be released :)
