### ISSUE TITLE
httpResponseCode is not used in v10

### ISSUE THREAD

**Issue by tgriessbach** [Leuchtfeuer/locate#30]
In typoscript it is possible to set a "httpResponseCode"

This is saved to `$config['settings']['responseCode']` here:
https://github.com/Leuchtfeuer/locate/blob/dev-10.0/Classes/Middleware/LanguageRedirectMiddleware.php#L54

But the `locate/Classes/Action/Redirect.php->process()`  checks for the original name and casts it to (int) although it should be a string like "HTTP/1.1 301 Moved Permanently"

`$this->httpStatus = $this->configuration['httpResponseCode'] ? (int)$this->configuration['httpResponseCode'] : HttpUtility::HTTP_STATUS_301;`

**Comment by elbebass** [comment]
Release with https://github.com/Leuchtfeuer/locate/releases/tag/v10.0.3
