### ISSUE TITLE
Installation Breaks Typo3 11

### ISSUE THREAD

**Issue by JohnBrammas** [Leuchtfeuer/locate#38]
**Describe the bug**
**To Reproduce**
In a clean Typo3 11 installation I added the first the "static_info_tables"-Extension then locate.
I get an error 503. Same with a Typo3 10 installation.
After setting the "Configuration Presetsto" to "debug" I get the error:

Class "Leuchtfeuer\Locate\Domain\Repository\RegionRepository" not found
in [PATH_TO_DIRECTORY]/typo3conf/ext/locate/Configuration/TCA/Overrides/pages.php line 23

Further Information: Linux-System with PHP Version 8.0.22, the Typo3 system is installed with the symbolic link method. The extensions are added with the backend tool.

**Comment by davkraid** [comment]
Thanks for your feedback. This sounds like an autoload problem, not a problem with the extension itself. I've installed the current version of the extension in a clean TYPO3 10 and 11 (via composer) and I can't reproduce the problem.
