### ISSUE TITLE
Errors after update TYPO3 update v11.5 und PHP 8.1

### ISSUE THREAD

**Issue by derBoogie** [Leuchtfeuer/locate#40]
After the Update to PHP 8.1 (TYPO3 11.5) the following errors are thrown:

1. PHP Warning: Undefined array key "tx_locate" in /html/typo3/typo3conf/ext/locate/Classes/Middleware/LanguageRedirectMiddleware.php line 34

2. PHP Warning: Attempt to read property "user" on null in /html/typo3/typo3conf/ext/locate/Classes/Middleware/PageUnavailableMiddleware.php line 39

**Comment by davkraid** [comment]
Thank you! Fixed in https://github.com/Leuchtfeuer/locate/commit/776a7811358dbeb3dbe6895ceb05a676316f6c5e.

**Comment by derBoogie** [comment]
Thank you for the quick fix!

**Comment by derBoogie** [comment]
After the update to locate v11.0.0 the changes from the patch 776a781 are no longer there.

**Comment by davkraid** [comment]
It will be in the next release tag of the extension in the next days.
