### ISSUE TITLE
Going without a decision/verdict should not trigger an error-logging

### ISSUE THREAD

**Issue by neufeind** [Leuchtfeuer/locate#43]
We have a judge (based on AbstractJudge) that checks if some redirects should take place. If not it simply returns $this without setting a decision/verdict. In court.php that triggers:

  No verdict should be delivered. This might be a problem in you configuration

That happens if decision is not set or if the verdict is not set. Imho it should be possible to take no decision. Otherwise we'd maybe need a "null-decision"?

**Comment by davkraid** [comment]
Good point. It's also a problem for the Condition Judge because if there is no matching condition and no Fixed Judge set, is also triggers the error logging. Thanks for your PR!
