### ISSUE TITLE
Support for TYPO3v12 LTS

### ISSUE THREAD

**Issue by patriciaschierling** [Leuchtfeuer/locate#47]
Are there any plans to upgrade the extension for TYPO3 12?

**Comment by balasch** [comment]
That will surely come. But we don't have a timetable yet for when exactly we will adapt it.
Sponsoring could speed up the process. ;-)

**Comment by sfech** [comment]
Hi, 

is there anything new regarding the upgrade for the extension yet?

**Comment by davkraid** [comment]
Fresh out of the oven: https://github.com/Leuchtfeuer/locate/releases/tag/v12.0.0 :)

**Comment by sfech** [comment]
That's great news, thank you very much. :)
