### ISSUE TITLE
Don't redirect for sitemap.xml urls

### ISSUE THREAD

**Issue by instruccionesaldorso** [Leuchtfeuer/locate#61]
TYPO3 12.4.22
EXT:locate 12.0.3

Hi hi. I'm using extension EXT:locate in a v12 installation. When accessing a specific sitemap.xml e.g. https://www.example.com/ch/sitemap.xml different than the GeoIP version I'm in e.g. Germany, it redirects to homepage in german https://www.example.com/de 
How could I force that the redirection is not made for sitemap.xml urls?

**Comment by balasch** [comment]
if you use the TYPO3 integrated sitemap function, this TypoScript should work here:

```
[getTSFE().type == 1533906435]
    config.tx_locate = 0
[end]
```

**Comment by instruccionesaldorso** [comment]
Thanks for the hint, @balasch 
That works like a charm!
Great extension, by the way! I needed a replacement in v12 for EXT:ipandlanguageredirect

To be more precise, as this condition is not working in BE context properly (the function getTSFE() does not work in the BE context, because the TSFE global object only exists in the FE context), I changed the condition to:

```
[getTSFE()?.type == 1533906435]
```

(using the null-safe operator)

**Comment by balasch** [comment]
Oops, you're right. Out of laziness, I took a snippet from a v11 project earlier. Thanks for your hint.
