### ISSUE TITLE
Problems with cache

### ISSUE THREAD

**Issue by niederberger-qw** [Leuchtfeuer/locate#64]
**Describe the bug**
With an IP address from the USA simulated by Browserstack, the redirect only works after the cache has been emptied.

**To Reproduce**
We have set it up so that the Locate extension is only activated on the German start page.
[page["sys_language_uid"] == 0] AND [page["uid"] == 1]
    config.tx_locate = 1
[end]

**Expected behavior**
Redirect only on the German homepage.

**Additional context**
The redirect works, but only after you have cleared the cache. After that, you can access the German page without any problems and even with a new browser session. A redirect no longer takes place.

**Comment by davkraid** [comment]
It seems that this is not a bug in the extension but a TYPO3 cache behaviour. If Typoscript is adapated, the TYPO3 frontend cache has to be cleared to take in effect.
